name: HTML Proofer

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install HTMLProofer
        run: gem install html-proofer

      - name: Run HTMLProofer
        run: htmlproofer ./_site --disable-external
