on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
  pull_request_target:
    types:
      - closed

jobs: 
  check-migration:
    name: Migration detection
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read    
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check migration
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '^prisma/' || true)
          
          if ! [ -n "$CHANGED" ]; then
            curl -s -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
              -d '{
                "state": "success",
                "context": "migrations/check",
                "description": "Migrations passed"
              }'
          fi
